# Generated by Django 4.0.4 on 2024-12-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_crop_lister_id_crop_lister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
