# Generated by Django 4.0.4 on 2024-12-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_crop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
