# Generated by Django 4.0.4 on 2024-12-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_crop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
