# Generated by Django 4.0.4 on 2024-12-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
