# Generated by Django 4.0.4 on 2024-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_crop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
