# Generated by Django 4.0.4 on 2024-12-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_paymentmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subTotal',
        ),
    ]
