# Generated by Django 4.0.4 on 2024-12-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
